<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>auxim</AssemblyName>
    <RootNamespace>Auxim.Cli</RootNamespace>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auxim.Core\Auxim.Core.csproj" />
    <ProjectReference Include="..\Auxim.Agent\Auxim.Agent.csproj" />
  </ItemGroup>
</Project>
