name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        solution: [Auxim.Kernel.sln, Auxim.Agent.sln]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore ${{ matrix.solution }}
        run: dotnet restore ${{ matrix.solution }}

      - name: Build ${{ matrix.solution }}
        run: dotnet build ${{ matrix.solution }} --no-restore -c Release

      - name: Test ${{ matrix.solution }}
        run: dotnet test ${{ matrix.solution }} --no-build -c Release --verbosity normal
